[book]
authors = ["Pesho Ivanov"]
language = "en"
multilingual = false
src = "src"
title = "Sequence alignment tutorial"

[preprocessor.bib]
bibliography = "biblio.bib"

[output.html.fold]
enable = true
