[book]
authors = ["Pesho Ivanov"]
language = "en"
multilingual = false
src = "src"
title = "Sequence alignment tutorial"

[output.html]
default-theme = "rust"
mathjax-support = true
git-repository-url = "https://github.com/pesho-ivanov/alignment-tutorial"
edit-url-template = "https://github.com/pesho-ivanov/alignment-tutorial/edit/main/{path}"
curly-quotes = true

[output.html.fold]
enable = true
level = 0         # the depth to start folding
