site_name: Sequence alignment tutorial
site_url: https://pesho-ivanov.github.io/alignment-tutorial/
site_author: Pesho Ivanov
site_description: >-
    Learn algorithms on the most basic task in Computational biology.

repo_name: pesho-ivanov/alignment-tutorial
repo_url: https://github.com/pesho-ivanov/alignment-tutorial

copyright: Copyright &copy; 2023 - 2023 Pesho Ivanov

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tracking

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
