site_name: Sequence alignment tutorial
site_url: https://pesho-ivanov.github.io/alignment-tutorial/
site_author: Pesho Ivanov
site_description: >-
    Learn algorithms on the most basic task in Computational biology.

repo_name: pesho-ivanov/alignment-tutorial
repo_url: https://github.com/pesho-ivanov/alignment-tutorial

copyright: Copyleft 🄯 2023 - 2023 Pesho Ivanov

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pesho-ivanov
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peshotrie

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - bibtex:
      bib_file: "docs/biblio.bib"

markdown_extensions:
  - smarty
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#* [Genome assembly](.)
#    * [Problem](.)
#    * [Data structures](.)
#        * [De Bruijn Graphs](.)
#        * [String graphs](.)
#    * [Paths: Hamiltonian, Eulerian](.)
#    * [Phylogenetic trees](.)
#    * [Minimal spanning trees (MST)](.)
#    * [Scaling](.)
#        * [Exponential possible solutions](.)
#        * [Near-quadratic in the worst case](.)
#        * [Other theoretical results](.)
#        * [Asymptotic behavior](.)
#        * [Empyrical behavior](.)
#        * [Other frameworks](.)
#    * [Verkko (tool)](.)
